trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13'
  displayName: 'Install Python 3.13'

- script: |
    python -m venv antenv
    source antenv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies in Virtual Environment'

- script: |
    echo "MONGO_URI=$MONGO_URI" > .env
  displayName: 'Generate Environment Configuration'
  env:
    MONGO_URI: $(MONGO_URI)

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  displayName: 'Deploy Academic Evaluator'
  inputs:
    azureSubscription: 'AcademicEvaluatorSC'
    appName: 'academic-evaluator'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'